/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GirisRouteImport } from './routes/giris'
import { Route as ApiAnalyzeDesignRouteImport } from './routes/api.analyze-design'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GirisRoute = GirisRouteImport.update({
  id: '/giris',
  path: '/giris',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeDesignRoute = ApiAnalyzeDesignRouteImport.update({
  id: '/api/analyze-design',
  path: '/api/analyze-design',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/giris': typeof GirisRoute
  '/api/analyze-design': typeof ApiAnalyzeDesignRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/giris': typeof GirisRoute
  '/api/analyze-design': typeof ApiAnalyzeDesignRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/giris': typeof GirisRoute
  '/api/analyze-design': typeof ApiAnalyzeDesignRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/giris' | '/api/analyze-design'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/giris' | '/api/analyze-design'
  id: '__root__' | '/' | '/giris' | '/api/analyze-design'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GirisRoute: typeof GirisRoute
  ApiAnalyzeDesignRoute: typeof ApiAnalyzeDesignRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giris': {
      id: '/giris'
      path: '/giris'
      fullPath: '/giris'
      preLoaderRoute: typeof GirisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze-design': {
      id: '/api/analyze-design'
      path: '/api/analyze-design'
      fullPath: '/api/analyze-design'
      preLoaderRoute: typeof ApiAnalyzeDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GirisRoute: GirisRoute,
  ApiAnalyzeDesignRoute: ApiAnalyzeDesignRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
