/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GirisRouteImport } from './routes/giris'
import { Route as ApiAnalyzeDesignRouteImport } from './routes/api.analyze-design'
import { Route as ApiGenerateReadingTestRouteImport } from './routes/api.generate-reading-test'
import { Route as ApiGroqAssistantRouteImport } from './routes/api.groq-assistant'
import { Route as ApiTranslateRouteImport } from './routes/api.translate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GirisRoute = GirisRouteImport.update({
  id: '/giris',
  path: '/giris',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeDesignRoute = ApiAnalyzeDesignRouteImport.update({
  id: '/api/analyze-design',
  path: '/api/analyze-design',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateReadingTestRoute = ApiGenerateReadingTestRouteImport.update({
  id: '/api/generate-reading-test',
  path: '/api/generate-reading-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGroqAssistantRoute = ApiGroqAssistantRouteImport.update({
  id: '/api/groq-assistant',
  path: '/api/groq-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranslateRoute = ApiTranslateRouteImport.update({
  id: '/api/translate',
  path: '/api/translate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/giris': typeof GirisRoute
  '/api/analyze-design': typeof ApiAnalyzeDesignRoute
  '/api/generate-reading-test': typeof ApiGenerateReadingTestRoute
  '/api/groq-assistant': typeof ApiGroqAssistantRoute
  '/api/translate': typeof ApiTranslateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/giris': typeof GirisRoute
  '/api/analyze-design': typeof ApiAnalyzeDesignRoute
  '/api/generate-reading-test': typeof ApiGenerateReadingTestRoute
  '/api/groq-assistant': typeof ApiGroqAssistantRoute
  '/api/translate': typeof ApiTranslateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/giris': typeof GirisRoute
  '/api/analyze-design': typeof ApiAnalyzeDesignRoute
  '/api/generate-reading-test': typeof ApiGenerateReadingTestRoute
  '/api/groq-assistant': typeof ApiGroqAssistantRoute
  '/api/translate': typeof ApiTranslateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/giris'
    | '/api/analyze-design'
    | '/api/generate-reading-test'
    | '/api/groq-assistant'
    | '/api/translate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/giris'
    | '/api/analyze-design'
    | '/api/generate-reading-test'
    | '/api/groq-assistant'
    | '/api/translate'
  id:
    | '__root__'
    | '/'
    | '/giris'
    | '/api/analyze-design'
    | '/api/generate-reading-test'
    | '/api/groq-assistant'
    | '/api/translate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GirisRoute: typeof GirisRoute
  ApiAnalyzeDesignRoute: typeof ApiAnalyzeDesignRoute
  ApiGenerateReadingTestRoute: typeof ApiGenerateReadingTestRoute
  ApiGroqAssistantRoute: typeof ApiGroqAssistantRoute
  ApiTranslateRoute: typeof ApiTranslateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giris': {
      id: '/giris'
      path: '/giris'
      fullPath: '/giris'
      preLoaderRoute: typeof GirisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze-design': {
      id: '/api/analyze-design'
      path: '/api/analyze-design'
      fullPath: '/api/analyze-design'
      preLoaderRoute: typeof ApiAnalyzeDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-reading-test': {
      id: '/api/generate-reading-test'
      path: '/api/generate-reading-test'
      fullPath: '/api/generate-reading-test'
      preLoaderRoute: typeof ApiGenerateReadingTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/groq-assistant': {
      id: '/api/groq-assistant'
      path: '/api/groq-assistant'
      fullPath: '/api/groq-assistant'
      preLoaderRoute: typeof ApiGroqAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/translate': {
      id: '/api/translate'
      path: '/api/translate'
      fullPath: '/api/translate'
      preLoaderRoute: typeof ApiTranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GirisRoute: GirisRoute,
  ApiAnalyzeDesignRoute: ApiAnalyzeDesignRoute,
  ApiGenerateReadingTestRoute: ApiGenerateReadingTestRoute,
  ApiGroqAssistantRoute: ApiGroqAssistantRoute,
  ApiTranslateRoute: ApiTranslateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
